spring:
  application:
    name: email-notification-service
  kafka:
    consumer:
        bootstrap-servers: localhost:9092,localhost:9094
        group-id: product-created-event
        key-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
        value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
        properties:
          spring:
            json:
              trusted:
                packages: '*'

server:
  port: 8082