spring:
  application:
    name: email-notification-service
  kafka:
    consumer:
        bootstrap-servers: localhost:9092,localhost:9094
        group-id: product-created-event

server:
  port: 8088